// Code generated by go run ./internal/gen; DO NOT EDIT.

package gooq

// Record6 holds 6 typed column values.
type Record6[T1, T2, T3, T4, T5, T6 any] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
}

func (r Record6[T1, T2, T3, T4, T5, T6]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6}
}

func (r Record6[T1, T2, T3, T4, T5, T6]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	}
	return nil
}

// Record7 holds 7 typed column values.
type Record7[T1, T2, T3, T4, T5, T6, T7 any] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
}

func (r Record7[T1, T2, T3, T4, T5, T6, T7]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7}
}

func (r Record7[T1, T2, T3, T4, T5, T6, T7]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	}
	return nil
}

// Record8 holds 8 typed column values.
type Record8[T1, T2, T3, T4, T5, T6, T7, T8 any] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
}

func (r Record8[T1, T2, T3, T4, T5, T6, T7, T8]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8}
}

func (r Record8[T1, T2, T3, T4, T5, T6, T7, T8]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	}
	return nil
}

// Record9 holds 9 typed column values.
type Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9 any] struct {
	V1 T1
	V2 T2
	V3 T3
	V4 T4
	V5 T5
	V6 T6
	V7 T7
	V8 T8
	V9 T9
}

func (r Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9}
}

func (r Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	}
	return nil
}

// Record10 holds 10 typed column values.
type Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
}

func (r Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10}
}

func (r Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	}
	return nil
}

// Record11 holds 11 typed column values.
type Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
}

func (r Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11}
}

func (r Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	}
	return nil
}

// Record12 holds 12 typed column values.
type Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
}

func (r Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12}
}

func (r Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	}
	return nil
}

// Record13 holds 13 typed column values.
type Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
}

func (r Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13}
}

func (r Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	}
	return nil
}

// Record14 holds 14 typed column values.
type Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
}

func (r Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14}
}

func (r Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	}
	return nil
}

// Record15 holds 15 typed column values.
type Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
}

func (r Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15}
}

func (r Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	}
	return nil
}

// Record16 holds 16 typed column values.
type Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
}

func (r Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16}
}

func (r Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	}
	return nil
}

// Record17 holds 17 typed column values.
type Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
}

func (r Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17}
}

func (r Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	}
	return nil
}

// Record18 holds 18 typed column values.
type Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
}

func (r Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17, r.V18}
}

func (r Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	case 17:
		return r.V18
	}
	return nil
}

// Record19 holds 19 typed column values.
type Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
}

func (r Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17, r.V18, r.V19}
}

func (r Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	case 17:
		return r.V18
	case 18:
		return r.V19
	}
	return nil
}

// Record20 holds 20 typed column values.
type Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
	V20 T20
}

func (r Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17, r.V18, r.V19, r.V20}
}

func (r Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	case 17:
		return r.V18
	case 18:
		return r.V19
	case 19:
		return r.V20
	}
	return nil
}

// Record21 holds 21 typed column values.
type Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
	V20 T20
	V21 T21
}

func (r Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17, r.V18, r.V19, r.V20, r.V21}
}

func (r Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	case 17:
		return r.V18
	case 18:
		return r.V19
	case 19:
		return r.V20
	case 20:
		return r.V21
	}
	return nil
}

// Record22 holds 22 typed column values.
type Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22 any] struct {
	V1  T1
	V2  T2
	V3  T3
	V4  T4
	V5  T5
	V6  T6
	V7  T7
	V8  T8
	V9  T9
	V10 T10
	V11 T11
	V12 T12
	V13 T13
	V14 T14
	V15 T15
	V16 T16
	V17 T17
	V18 T18
	V19 T19
	V20 T20
	V21 T21
	V22 T22
}

func (r Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22]) Values() []any {
	return []any{r.V1, r.V2, r.V3, r.V4, r.V5, r.V6, r.V7, r.V8, r.V9, r.V10, r.V11, r.V12, r.V13, r.V14, r.V15, r.V16, r.V17, r.V18, r.V19, r.V20, r.V21, r.V22}
}

func (r Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22]) Get(i int) any {
	switch i {
	case 0:
		return r.V1
	case 1:
		return r.V2
	case 2:
		return r.V3
	case 3:
		return r.V4
	case 4:
		return r.V5
	case 5:
		return r.V6
	case 6:
		return r.V7
	case 7:
		return r.V8
	case 8:
		return r.V9
	case 9:
		return r.V10
	case 10:
		return r.V11
	case 11:
		return r.V12
	case 12:
		return r.V13
	case 13:
		return r.V14
	case 14:
		return r.V15
	case 15:
		return r.V16
	case 16:
		return r.V17
	case 17:
		return r.V18
	case 18:
		return r.V19
	case 19:
		return r.V20
	case 20:
		return r.V21
	case 21:
		return r.V22
	}
	return nil
}
