// Code generated by go run ./internal/gen; DO NOT EDIT.

package gooq

import "database/sql"

// Select6 begins a SELECT projecting 6 typed columns.
func Select6[T1, T2, T3, T4, T5, T6 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6]) SelectFromStep[Record6[T1, T2, T3, T4, T5, T6]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6}, func(rows *sql.Rows) (Record6[T1, T2, T3, T4, T5, T6], error) {
		var r Record6[T1, T2, T3, T4, T5, T6]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6)
		return r, err
	})
}

// Select7 begins a SELECT projecting 7 typed columns.
func Select7[T1, T2, T3, T4, T5, T6, T7 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7]) SelectFromStep[Record7[T1, T2, T3, T4, T5, T6, T7]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7}, func(rows *sql.Rows) (Record7[T1, T2, T3, T4, T5, T6, T7], error) {
		var r Record7[T1, T2, T3, T4, T5, T6, T7]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7)
		return r, err
	})
}

// Select8 begins a SELECT projecting 8 typed columns.
func Select8[T1, T2, T3, T4, T5, T6, T7, T8 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8]) SelectFromStep[Record8[T1, T2, T3, T4, T5, T6, T7, T8]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8}, func(rows *sql.Rows) (Record8[T1, T2, T3, T4, T5, T6, T7, T8], error) {
		var r Record8[T1, T2, T3, T4, T5, T6, T7, T8]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8)
		return r, err
	})
}

// Select9 begins a SELECT projecting 9 typed columns.
func Select9[T1, T2, T3, T4, T5, T6, T7, T8, T9 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9]) SelectFromStep[Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9}, func(rows *sql.Rows) (Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9], error) {
		var r Record9[T1, T2, T3, T4, T5, T6, T7, T8, T9]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9)
		return r, err
	})
}

// Select10 begins a SELECT projecting 10 typed columns.
func Select10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10]) SelectFromStep[Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10}, func(rows *sql.Rows) (Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10], error) {
		var r Record10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10)
		return r, err
	})
}

// Select11 begins a SELECT projecting 11 typed columns.
func Select11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11]) SelectFromStep[Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11}, func(rows *sql.Rows) (Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11], error) {
		var r Record11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11)
		return r, err
	})
}

// Select12 begins a SELECT projecting 12 typed columns.
func Select12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12]) SelectFromStep[Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12}, func(rows *sql.Rows) (Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12], error) {
		var r Record12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12)
		return r, err
	})
}

// Select13 begins a SELECT projecting 13 typed columns.
func Select13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13]) SelectFromStep[Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13}, func(rows *sql.Rows) (Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13], error) {
		var r Record13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13)
		return r, err
	})
}

// Select14 begins a SELECT projecting 14 typed columns.
func Select14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14]) SelectFromStep[Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14}, func(rows *sql.Rows) (Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14], error) {
		var r Record14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14)
		return r, err
	})
}

// Select15 begins a SELECT projecting 15 typed columns.
func Select15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15]) SelectFromStep[Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15}, func(rows *sql.Rows) (Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15], error) {
		var r Record15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15)
		return r, err
	})
}

// Select16 begins a SELECT projecting 16 typed columns.
func Select16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16]) SelectFromStep[Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16}, func(rows *sql.Rows) (Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16], error) {
		var r Record16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16)
		return r, err
	})
}

// Select17 begins a SELECT projecting 17 typed columns.
func Select17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17]) SelectFromStep[Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17}, func(rows *sql.Rows) (Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17], error) {
		var r Record17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17)
		return r, err
	})
}

// Select18 begins a SELECT projecting 18 typed columns.
func Select18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17], f18 Field[T18]) SelectFromStep[Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18}, func(rows *sql.Rows) (Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18], error) {
		var r Record18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17, &r.V18)
		return r, err
	})
}

// Select19 begins a SELECT projecting 19 typed columns.
func Select19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17], f18 Field[T18], f19 Field[T19]) SelectFromStep[Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19}, func(rows *sql.Rows) (Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19], error) {
		var r Record19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17, &r.V18, &r.V19)
		return r, err
	})
}

// Select20 begins a SELECT projecting 20 typed columns.
func Select20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17], f18 Field[T18], f19 Field[T19], f20 Field[T20]) SelectFromStep[Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20}, func(rows *sql.Rows) (Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20], error) {
		var r Record20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17, &r.V18, &r.V19, &r.V20)
		return r, err
	})
}

// Select21 begins a SELECT projecting 21 typed columns.
func Select21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17], f18 Field[T18], f19 Field[T19], f20 Field[T20], f21 Field[T21]) SelectFromStep[Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21}, func(rows *sql.Rows) (Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21], error) {
		var r Record21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17, &r.V18, &r.V19, &r.V20, &r.V21)
		return r, err
	})
}

// Select22 begins a SELECT projecting 22 typed columns.
func Select22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22 any](f1 Field[T1], f2 Field[T2], f3 Field[T3], f4 Field[T4], f5 Field[T5], f6 Field[T6], f7 Field[T7], f8 Field[T8], f9 Field[T9], f10 Field[T10], f11 Field[T11], f12 Field[T12], f13 Field[T13], f14 Field[T14], f15 Field[T15], f16 Field[T16], f17 Field[T17], f18 Field[T18], f19 Field[T19], f20 Field[T20], f21 Field[T21], f22 Field[T22]) SelectFromStep[Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22]] {
	return newSelect([]node{f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22}, func(rows *sql.Rows) (Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22], error) {
		var r Record22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22]
		err := rows.Scan(&r.V1, &r.V2, &r.V3, &r.V4, &r.V5, &r.V6, &r.V7, &r.V8, &r.V9, &r.V10, &r.V11, &r.V12, &r.V13, &r.V14, &r.V15, &r.V16, &r.V17, &r.V18, &r.V19, &r.V20, &r.V21, &r.V22)
		return r, err
	})
}
