package codegen

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// collapse reduces every run of whitespace to a single space and trims the
// result, so golden fragment checks are insensitive to gofmt's exact spacing.
func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func TestEmitTableGolden(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "title", DataType: "text"},
			{Name: "price", DataType: "numeric(10,2)"},
			{Name: "author_id", DataType: "integer"},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	got := collapse(source)

	fragments := []string{
		"// Code generated by gooq-gen; DO NOT EDIT.",
		"package db",
		`"github.com/cgardev/gooq"`,
		"type bookTable struct {",
		"gooq.TableImpl",
		"Id gooq.NumericField[int64]",
		"Title gooq.StringField",
		"Price gooq.NumericField[float64]",
		"AuthorId gooq.NumericField[int64]",
		`base := gooq.NewTable("book").WithAlias(alias)`,
		`Id: gooq.NewNumericField[int64](base, "id"),`,
		`Title: gooq.NewStringField(base, "title"),`,
		`Price: gooq.NewNumericField[float64](base, "price"),`,
		`AuthorId: gooq.NewNumericField[int64](base, "author_id"),`,
		"func (t *bookTable) As(alias string) *bookTable { return newBookTable(alias) }",
		`var Book = newBookTable("")`,
	}
	for _, f := range fragments {
		if !strings.Contains(got, collapse(f)) {
			t.Errorf("emitted source missing fragment:\n%s\n--- got ---\n%s", f, source)
		}
	}
}

func TestEmitTableImportsTime(t *testing.T) {
	table := TableSchema{
		Name: "event",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "created_at", DataType: "timestamp with time zone"},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	got := collapse(source)

	if !strings.Contains(got, `"time"`) {
		t.Errorf("expected the time import, got:\n%s", source)
	}
	if !strings.Contains(got, "CreatedAt gooq.Field[time.Time]") {
		t.Errorf("expected a time.Time field, got:\n%s", source)
	}
}

// TestEmitTableNullableColumns verifies that nullable scalar columns are
// rendered as plain fields wrapping the generic sql.Null type and that the
// generated source imports the database/sql package. Nullable JSON columns are
// left unwrapped.
func TestEmitTableNullableColumns(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "bigint", Nullable: false},
			{Name: "subtitle", DataType: "text", Nullable: true},
			{Name: "published_at", DataType: "timestamp with time zone", Nullable: true},
			{Name: "reviews", DataType: "bigint", Nullable: true},
			{Name: "metadata", DataType: "jsonb", Nullable: true},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	got := collapse(source)

	fragments := []string{
		`"database/sql"`,
		`"time"`,
		"Subtitle gooq.Field[sql.Null[string]]",
		`Subtitle: gooq.NewField[sql.Null[string]](base, "subtitle"),`,
		"PublishedAt gooq.Field[sql.Null[time.Time]]",
		`PublishedAt: gooq.NewField[sql.Null[time.Time]](base, "published_at"),`,
		"Reviews gooq.Field[sql.Null[int64]]",
		`Reviews: gooq.NewField[sql.Null[int64]](base, "reviews"),`,
		// A nullable json/jsonb column maps to a plain []byte (not
		// json.RawMessage) because database/sql cannot scan a NULL into a named
		// slice type.
		"Metadata gooq.Field[[]byte]",
		`Metadata: gooq.NewField[[]byte](base, "metadata"),`,
	}
	for _, f := range fragments {
		if !strings.Contains(got, collapse(f)) {
			t.Errorf("emitted source missing fragment:\n%s\n--- got ---\n%s", f, source)
		}
	}

	// This table has no non-nullable json column, so encoding/json must not be
	// imported.
	if strings.Contains(got, `"encoding/json"`) {
		t.Errorf("did not expect the encoding/json import:\n%s", source)
	}
}

// TestEmitTableCompiles asserts that the emitted source parses as valid Go. A
// full type check would require resolving the jooq import, so parsing is used as
// the lightweight proof of syntactic validity.
func TestEmitTableCompiles(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "title", DataType: "text"},
			{Name: "created_at", DataType: "timestamp"},
			{Name: "payload", DataType: "jsonb"},
			{Name: "subtitle", DataType: "text", Nullable: true},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "book.gen.go")
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, path, nil, parser.AllErrors); err != nil {
		t.Fatalf("emitted source does not parse: %v\n--- source ---\n%s", err, source)
	}
}
