package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// gooqImport is the import path of the runtime jooq package whose field types
// the generated code references.
const gooqImport = "github.com/cgardev/gooq"

// TypeOverride directs the generator to map a column or SQL type onto a specific
// Go type instead of the default mapping. GoType is the Go type expression used
// as the field element, for example "uuid.UUID". Import, when non-empty, is the
// package import path that provides the type, for example
// "github.com/google/uuid".
type TypeOverride struct {
	// GoType is the Go type expression to use as the field element type.
	GoType string
	// Import is the package import path providing GoType, or empty when GoType
	// names a builtin or already-imported type.
	Import string
}

// templateColumn is the per-column view passed to the emission template.
type templateColumn struct {
	// Field is the exported Go struct field name, such as "AuthorId".
	Field string
	// Type is the Go field type, such as "gooq.NumericField[int64]".
	Type string
	// Constructor is the jooq constructor for the field, such as
	// "gooq.NewNumericField[int64]".
	Constructor string
	// Column is the unqualified database column name.
	Column string
}

// templateForeignKey is the per-foreign-key view passed to the table template.
type templateForeignKey struct {
	// Name is the constraint name.
	Name string
	// Columns is the Go literal of the local column names.
	Columns string
	// RefTable is the referenced table name.
	RefTable string
	// RefColumns is the Go literal of the referenced column names.
	RefColumns string
}

// templateTable is the whole-table view passed to the emission template.
type templateTable struct {
	Package         string
	Imports         []string
	StructName      string
	ConstructorName string
	ExportName      string
	TableName       string
	IsView          bool
	Columns         []templateColumn
	PrimaryKey      string
	UniquesLiteral  string
	ForeignKeys     []templateForeignKey
}

// tableTemplateText renders a single generated table file. The layout
// intentionally mirrors the hand-checked golden files so that running gofmt over
// the output reproduces them exactly. Base tables additionally emit PrimaryKey,
// Uniques, and ForeignKeys metadata accessors; views emit only column accessors.
const tableTemplateText = `// Code generated by gooq-gen; DO NOT EDIT.

package {{.Package}}

import (
{{range .Imports}}	"{{.}}"
{{end}})

// {{.StructName}} is the generated typed accessor for the "{{.TableName}}" {{if .IsView}}view{{else}}table{{end}}.
type {{.StructName}} struct {
	gooq.TableImpl
{{range .Columns}}	{{.Field}} {{.Type}}
{{end}}}

func {{.ConstructorName}}(alias string) *{{.StructName}} {
	base := gooq.NewTable("{{.TableName}}").WithAlias(alias)
	return &{{.StructName}}{
		TableImpl: base,
{{range .Columns}}		{{.Field}}: {{.Constructor}}(base, "{{.Column}}"),
{{end}}	}
}

// As returns the {{if .IsView}}view{{else}}table{{end}} under an alias, with every column re-qualified.
func (t *{{.StructName}}) As(alias string) *{{.StructName}} { return {{.ConstructorName}}(alias) }
{{if not .IsView}}
// PrimaryKey returns the primary key column names in key order.
func (t *{{.StructName}}) PrimaryKey() []string { return {{.PrimaryKey}} }

// Uniques returns each unique constraint as its ordered column names.
func (t *{{.StructName}}) Uniques() [][]string { return {{.UniquesLiteral}} }

// ForeignKeys returns the foreign key constraints declared on the table.
func (t *{{.StructName}}) ForeignKeys() []gooq.ForeignKeyMeta {
	return []gooq.ForeignKeyMeta{ {{range .ForeignKeys}}
		{Name: "{{.Name}}", Columns: {{.Columns}}, RefTable: "{{.RefTable}}", RefColumns: {{.RefColumns}}},{{end}}
	}
}
{{end}}
// {{.ExportName}} is the package-level accessor for the "{{.TableName}}" {{if .IsView}}view{{else}}table{{end}}.
var {{.ExportName}} = {{.ConstructorName}}("")
`

// tableTemplate is the parsed table template.
var tableTemplate = template.Must(template.New("table").Parse(tableTemplateText))

// titleFirst upper-cases the first rune of s, leaving the remainder unchanged.
// It converts an unexported struct name into its constructor suffix, for example
// "bookTable" into "BookTable" so that the constructor reads "newBookTable".
func titleFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] -= 'a' - 'A'
	}
	return string(runes)
}

// stringSliceLiteral renders a Go literal for a slice of strings, for example
// []string{"a", "b"}. An empty slice renders as nil so that empty key metadata
// reads naturally.
func stringSliceLiteral(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteString("[]string{")
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", v)
	}
	b.WriteString("}")
	return b.String()
}

// uniquesLiteral renders a Go literal for the unique constraint column sets,
// using the simplified inner element form so the output matches gofmt -s, for
// example [][]string{{"a"}, {"b", "c"}}. An empty set renders as nil.
func uniquesLiteral(uniques [][]string) string {
	if len(uniques) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteString("[][]string{")
	for i, u := range uniques {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString("{")
		for j, c := range u {
			if j > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", c)
		}
		b.WriteString("}")
	}
	b.WriteString("}")
	return b.String()
}

// enumTypeName returns the exported Go named type for a PostgreSQL enum type,
// such as "BookStatus" for the enum "book_status".
func enumTypeName(enum string) string {
	return safeIdent(camel(enum), "Enum")
}

// enumConstName returns the exported constant name for an enum label, combining
// the enum type name with the camel-cased label, such as "BookStatusInPrint"
// for the label "in_print" of the enum "book_status".
func enumConstName(enum, label string) string {
	return safeIdent(enumTypeName(enum)+camel(label), "EnumValue")
}

// overrideKeys returns the lookup keys that may select a type override for a
// column, most specific first: the fully qualified schema.table.column key and
// the normalized SQL type key.
func overrideKeys(schema, table string, col Column) []string {
	return []string{
		schema + "." + table + "." + col.Name,
		normalizeType(col.DataType),
	}
}

// resolveColumnMapping computes the field mapping for a column, applying a type
// override when one is configured and otherwise mapping the column's enum or SQL
// type. The returned mapping carries the field type, constructor, and imports.
func resolveColumnMapping(schema, table string, col Column, overrides map[string]TypeOverride) goMapping {
	for _, key := range overrideKeys(schema, table, col) {
		if ov, ok := overrides[key]; ok {
			var imports []string
			if ov.Import != "" {
				imports = []string{ov.Import}
			}
			return mapColumn(col, &goMapping{fieldType: ov.GoType, imports: imports})
		}
	}
	if col.EnumType != "" {
		return mapTypeMapping(mappingForElement(enumTypeName(col.EnumType), nil), col.Nullable)
	}
	return mapColumn(col, nil)
}

// EmitTable renders the generated source for one table or view into a package
// named pkg, using the default schema and no type overrides. The output is
// formatted with gofmt; if formatting fails, the unformatted source is returned
// alongside the error to aid debugging.
func EmitTable(pkg string, t TableSchema) (string, error) {
	return emitTable(pkg, "public", t, nil)
}

// emitTable is the internal entry point that also accepts the schema name and
// the configured type overrides. EmitTable preserves the original two-argument
// signature for backward compatibility and uses the default schema.
func emitTable(pkg, schema string, t TableSchema, overrides map[string]TypeOverride) (string, error) {
	imports := map[string]bool{gooqImport: true}

	columns := make([]templateColumn, 0, len(t.Columns))
	for _, c := range t.Columns {
		mapping := resolveColumnMapping(schema, t.Name, c, overrides)
		for _, imp := range mapping.imports {
			imports[imp] = true
		}
		columns = append(columns, templateColumn{
			Field:       fieldName(c.Name),
			Type:        mapping.fieldType,
			Constructor: mapping.constructor,
			Column:      c.Name,
		})
	}

	importPaths := make([]string, 0, len(imports))
	for imp := range imports {
		importPaths = append(importPaths, imp)
	}
	sort.Strings(importPaths)

	foreignKeys := make([]templateForeignKey, 0, len(t.ForeignKeys))
	for _, fk := range t.ForeignKeys {
		foreignKeys = append(foreignKeys, templateForeignKey{
			Name:       fk.Name,
			Columns:    stringSliceLiteral(fk.Columns),
			RefTable:   fk.RefTable,
			RefColumns: stringSliceLiteral(fk.RefColumns),
		})
	}

	sn := structName(t.Name)
	data := templateTable{
		Package:         pkg,
		Imports:         importPaths,
		StructName:      sn,
		ConstructorName: "new" + titleFirst(sn),
		ExportName:      exportName(t.Name),
		TableName:       t.Name,
		IsView:          t.IsView,
		Columns:         columns,
		PrimaryKey:      stringSliceLiteral(t.PrimaryKey),
		UniquesLiteral:  uniquesLiteral(t.Uniques),
		ForeignKeys:     foreignKeys,
	}

	var buf bytes.Buffer
	if err := tableTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering table %q: %w", t.Name, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting table %q: %w\n--- source ---\n%s", t.Name, err, buf.String())
	}
	return string(formatted), nil
}

// enumDefinition is the per-enum view used when emitting enum definitions.
type enumDefinition struct {
	// TypeName is the exported Go named type for the enum.
	TypeName string
	// RawName is the underlying PostgreSQL enum type name.
	RawName string
	// Constants are the label constants in declared order.
	Constants []enumConstant
}

// enumConstant is the per-label view used when emitting enum definitions.
type enumConstant struct {
	// Name is the exported Go constant name.
	Name string
	// Value is the database label value.
	Value string
}

// collectEnums returns the distinct enum definitions referenced by the tables,
// ordered by the underlying enum type name so the emitted file is deterministic.
func collectEnums(tables []TableSchema) []enumDefinition {
	seen := make(map[string]enumDefinition)
	for _, t := range tables {
		for _, c := range t.Columns {
			if c.EnumType == "" {
				continue
			}
			if _, ok := seen[c.EnumType]; ok {
				continue
			}
			constants := make([]enumConstant, 0, len(c.EnumLabels))
			for _, label := range c.EnumLabels {
				constants = append(constants, enumConstant{
					Name:  enumConstName(c.EnumType, label),
					Value: label,
				})
			}
			seen[c.EnumType] = enumDefinition{
				TypeName:  enumTypeName(c.EnumType),
				RawName:   c.EnumType,
				Constants: constants,
			}
		}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)

	definitions := make([]enumDefinition, 0, len(names))
	for _, name := range names {
		definitions = append(definitions, seen[name])
	}
	return definitions
}

// emitEnums renders the shared enum definitions file for a package, or returns
// the empty string when no enums are present. Each enum becomes a Go named
// string type with one constant per label, in declared order.
func emitEnums(pkg string, definitions []enumDefinition) (string, error) {
	if len(definitions) == 0 {
		return "", nil
	}

	var body bytes.Buffer
	body.WriteString("// Code generated by gooq-gen; DO NOT EDIT.\n\npackage ")
	body.WriteString(pkg)
	body.WriteString("\n")
	for _, def := range definitions {
		fmt.Fprintf(&body, "\n// %s is the Go named type for the %q enum.\n", def.TypeName, def.RawName)
		fmt.Fprintf(&body, "type %s string\n\nconst (\n", def.TypeName)
		for _, c := range def.Constants {
			fmt.Fprintf(&body, "\t%s %s = %q\n", c.Name, def.TypeName, c.Value)
		}
		body.WriteString(")\n")
	}

	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting enums: %w\n--- source ---\n%s", err, body.String())
	}
	return string(formatted), nil
}
