package codegen

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// collapse reduces every run of whitespace to a single space and trims the
// result, so golden fragment checks are insensitive to gofmt's exact spacing.
func collapse(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// assertFragments fails the test for every fragment not present in the collapsed
// source, reporting the missing fragment and the full source for context.
func assertFragments(t *testing.T, source string, fragments []string) {
	t.Helper()
	got := collapse(source)
	for _, f := range fragments {
		if !strings.Contains(got, collapse(f)) {
			t.Errorf("emitted source missing fragment:\n%s\n--- got ---\n%s", f, source)
		}
	}
}

func TestEmitTableGolden(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "title", DataType: "text"},
			{Name: "price", DataType: "numeric(10,2)"},
			{Name: "author_id", DataType: "integer"},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	assertFragments(t, source, []string{
		"// Code generated by gooq-gen; DO NOT EDIT.",
		"package db",
		`"github.com/cgardev/gooq"`,
		"type bookTable struct {",
		"gooq.TableImpl",
		"Id gooq.NumericField[int64]",
		"Title gooq.StringField",
		"Price gooq.NumericField[float64]",
		"AuthorId gooq.NumericField[int64]",
		`base := gooq.NewTable("book").WithAlias(alias)`,
		`Id: gooq.NewNumericField[int64](base, "id"),`,
		`Title: gooq.NewStringField(base, "title"),`,
		`Price: gooq.NewNumericField[float64](base, "price"),`,
		`AuthorId: gooq.NewNumericField[int64](base, "author_id"),`,
		"func (t *bookTable) As(alias string) *bookTable { return newBookTable(alias) }",
		`var Book = newBookTable("")`,
	})
}

func TestEmitTableImportsTime(t *testing.T) {
	table := TableSchema{
		Name: "event",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "created_at", DataType: "timestamp with time zone"},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	got := collapse(source)

	if !strings.Contains(got, `"time"`) {
		t.Errorf("expected the time import, got:\n%s", source)
	}
	if !strings.Contains(got, "CreatedAt gooq.Field[time.Time]") {
		t.Errorf("expected a time.Time field, got:\n%s", source)
	}
}

// TestEmitTableNullableColumns verifies that nullable scalar columns are
// rendered as plain fields wrapping the generic sql.Null type and that the
// generated source imports the database/sql package. Nullable JSON columns are
// left unwrapped.
func TestEmitTableNullableColumns(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "bigint", Nullable: false},
			{Name: "subtitle", DataType: "text", Nullable: true},
			{Name: "published_at", DataType: "timestamp with time zone", Nullable: true},
			{Name: "reviews", DataType: "bigint", Nullable: true},
			{Name: "metadata", DataType: "jsonb", Nullable: true},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	assertFragments(t, source, []string{
		`"database/sql"`,
		`"time"`,
		"Subtitle gooq.Field[sql.Null[string]]",
		`Subtitle: gooq.NewField[sql.Null[string]](base, "subtitle"),`,
		"PublishedAt gooq.Field[sql.Null[time.Time]]",
		`PublishedAt: gooq.NewField[sql.Null[time.Time]](base, "published_at"),`,
		"Reviews gooq.Field[sql.Null[int64]]",
		`Reviews: gooq.NewField[sql.Null[int64]](base, "reviews"),`,
		// A nullable json/jsonb column maps to a plain []byte (not
		// json.RawMessage) because database/sql cannot scan a NULL into a named
		// slice type.
		"Metadata gooq.Field[[]byte]",
		`Metadata: gooq.NewField[[]byte](base, "metadata"),`,
	})

	// This table has no non-nullable json column, so encoding/json must not be
	// imported.
	if strings.Contains(collapse(source), `"encoding/json"`) {
		t.Errorf("did not expect the encoding/json import:\n%s", source)
	}
}

// TestEmitTableKeyMetadata verifies that a base table emits the primary key,
// unique constraint, and foreign key metadata accessors with the simplified Go
// literals matching gofmt's output.
func TestEmitTableKeyMetadata(t *testing.T) {
	table := TableSchema{
		Name:       "book",
		PrimaryKey: []string{"id"},
		Uniques:    [][]string{{"isbn"}, {"author_id", "title"}},
		ForeignKeys: []ForeignKey{
			{Name: "book_author_id_fkey", Columns: []string{"author_id"}, RefTable: "author", RefColumns: []string{"id"}},
		},
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "author_id", DataType: "integer"},
			{Name: "title", DataType: "text"},
			{Name: "isbn", DataType: "text"},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	assertFragments(t, source, []string{
		`func (t *bookTable) PrimaryKey() []string { return []string{"id"} }`,
		`func (t *bookTable) Uniques() [][]string { return [][]string{{"isbn"}, {"author_id", "title"}} }`,
		"func (t *bookTable) ForeignKeys() []gooq.ForeignKeyMeta {",
		`{Name: "book_author_id_fkey", Columns: []string{"author_id"}, RefTable: "author", RefColumns: []string{"id"}},`,
	})
}

// TestEmitTableNoPrimaryKey verifies that a base table without a primary key or
// constraints emits the metadata accessors returning nil and an empty slice.
func TestEmitTableNoPrimaryKey(t *testing.T) {
	table := TableSchema{
		Name:    "log",
		Columns: []Column{{Name: "message", DataType: "text"}},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	assertFragments(t, source, []string{
		`func (t *logTable) PrimaryKey() []string { return nil }`,
		`func (t *logTable) Uniques() [][]string { return nil }`,
		"return []gooq.ForeignKeyMeta{",
	})
}

// TestEmitViewOmitsKeyMetadata verifies that a view emits only column accessors
// and no key metadata methods, and that its documentation reads as a view.
func TestEmitViewOmitsKeyMetadata(t *testing.T) {
	view := TableSchema{
		Name:   "book_summary",
		IsView: true,
		Columns: []Column{
			{Name: "title", DataType: "text"},
			{Name: "review_count", DataType: "bigint", Nullable: true},
		},
	}

	source, err := EmitTable("db", view)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	got := collapse(source)

	assertFragments(t, source, []string{
		`the "book_summary" view`,
		"Title gooq.StringField",
		"ReviewCount gooq.Field[sql.Null[int64]]",
		"func (t *bookSummaryTable) As(alias string) *bookSummaryTable { return newBookSummaryTable(alias) }",
		`var BookSummary = newBookSummaryTable("")`,
	})

	for _, method := range []string{"PrimaryKey()", "Uniques()", "ForeignKeys()"} {
		if strings.Contains(got, method) {
			t.Errorf("view unexpectedly emits %s:\n%s", method, source)
		}
	}
}

// TestEmitEnumColumn verifies that an enum column maps onto the generated named
// type and that the shared enum definitions file declares the type and its label
// constants in declared order.
func TestEmitEnumColumn(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "status", DataType: "USER-DEFINED", EnumType: "book_status",
				EnumLabels: []string{"draft", "in_print", "out_of_print"}},
			{Name: "next_status", DataType: "USER-DEFINED", Nullable: true, EnumType: "book_status",
				EnumLabels: []string{"draft", "in_print", "out_of_print"}},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}
	assertFragments(t, source, []string{
		"Status gooq.Field[BookStatus]",
		`Status: gooq.NewField[BookStatus](base, "status"),`,
		"NextStatus gooq.Field[sql.Null[BookStatus]]",
		`NextStatus: gooq.NewField[sql.Null[BookStatus]](base, "next_status"),`,
	})

	enums, err := emitEnums("db", collectEnums([]TableSchema{table}))
	if err != nil {
		t.Fatalf("emitEnums: %v", err)
	}
	assertFragments(t, enums, []string{
		"// Code generated by gooq-gen; DO NOT EDIT.",
		"type BookStatus string",
		`BookStatusDraft BookStatus = "draft"`,
		`BookStatusInPrint BookStatus = "in_print"`,
		`BookStatusOutOfPrint BookStatus = "out_of_print"`,
	})
}

// TestEmitTableTypeOverride verifies that a column-keyed override replaces the
// default type mapping and imports the override's package, while leaving other
// columns untouched.
func TestEmitTableTypeOverride(t *testing.T) {
	table := TableSchema{
		Name:       "book",
		PrimaryKey: []string{"id"},
		Columns: []Column{
			{Name: "id", DataType: "uuid"},
			{Name: "title", DataType: "text"},
		},
	}

	overrides := map[string]TypeOverride{
		"public.book.id": {GoType: "uuid.UUID", Import: "github.com/google/uuid"},
	}

	source, err := emitTable("db", "public", table, overrides)
	if err != nil {
		t.Fatalf("emitTable: %v", err)
	}
	assertFragments(t, source, []string{
		`"github.com/google/uuid"`,
		"Id gooq.Field[uuid.UUID]",
		`Id: gooq.NewField[uuid.UUID](base, "id"),`,
		// The non-overridden column keeps its default mapping.
		"Title gooq.StringField",
	})
}

// TestEmitTableTypeOverrideBySQLType verifies that an override keyed by the
// normalized SQL type applies to every column of that type when no more specific
// column key matches.
func TestEmitTableTypeOverrideBySQLType(t *testing.T) {
	table := TableSchema{
		Name: "book",
		Columns: []Column{
			{Name: "id", DataType: "uuid"},
			{Name: "author_id", DataType: "uuid"},
		},
	}

	overrides := map[string]TypeOverride{
		"uuid": {GoType: "uuid.UUID", Import: "github.com/google/uuid"},
	}

	source, err := emitTable("db", "public", table, overrides)
	if err != nil {
		t.Fatalf("emitTable: %v", err)
	}
	assertFragments(t, source, []string{
		"Id gooq.Field[uuid.UUID]",
		"AuthorId gooq.Field[uuid.UUID]",
	})
}

// TestEmitTableCompiles asserts that the emitted source parses as valid Go. A
// full type check would require resolving the jooq import, so parsing is used as
// the lightweight proof of syntactic validity.
func TestEmitTableCompiles(t *testing.T) {
	table := TableSchema{
		Name:       "book",
		PrimaryKey: []string{"id"},
		Uniques:    [][]string{{"title"}},
		ForeignKeys: []ForeignKey{
			{Name: "book_author_id_fkey", Columns: []string{"author_id"}, RefTable: "author", RefColumns: []string{"id"}},
		},
		Columns: []Column{
			{Name: "id", DataType: "integer"},
			{Name: "author_id", DataType: "integer"},
			{Name: "title", DataType: "text"},
			{Name: "created_at", DataType: "timestamp"},
			{Name: "payload", DataType: "jsonb"},
			{Name: "subtitle", DataType: "text", Nullable: true},
		},
	}

	source, err := EmitTable("db", table)
	if err != nil {
		t.Fatalf("EmitTable: %v", err)
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "book.gen.go")
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}

	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, path, nil, parser.AllErrors); err != nil {
		t.Fatalf("emitted source does not parse: %v\n--- source ---\n%s", err, source)
	}
}
