package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// gooqImport is the import path of the runtime jooq package whose field types
// the generated code references.
const gooqImport = "github.com/cgardev/gooq"

// templateColumn is the per-column view passed to the emission template.
type templateColumn struct {
	// Field is the exported Go struct field name, such as "AuthorId".
	Field string
	// Type is the Go field type, such as "gooq.NumericField[int64]".
	Type string
	// Constructor is the jooq constructor for the field, such as
	// "gooq.NewNumericField[int64]".
	Constructor string
	// Column is the unqualified database column name.
	Column string
}

// templateTable is the whole-table view passed to the emission template.
type templateTable struct {
	Package         string
	Imports         []string
	StructName      string
	ConstructorName string
	ExportName      string
	TableName       string
	Columns         []templateColumn
}

// tableTemplateText renders a single generated table file. The layout
// intentionally mirrors the hand-checked golden files so that running gofmt over
// the output reproduces them exactly.
const tableTemplateText = `// Code generated by gooq-gen; DO NOT EDIT.

package {{.Package}}

import (
{{range .Imports}}	"{{.}}"
{{end}})

// {{.StructName}} is the generated typed accessor for the "{{.TableName}}" table.
type {{.StructName}} struct {
	gooq.TableImpl
{{range .Columns}}	{{.Field}} {{.Type}}
{{end}}}

func {{.ConstructorName}}(alias string) *{{.StructName}} {
	base := gooq.NewTable("{{.TableName}}").WithAlias(alias)
	return &{{.StructName}}{
		TableImpl: base,
{{range .Columns}}		{{.Field}}: {{.Constructor}}(base, "{{.Column}}"),
{{end}}	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *{{.StructName}}) As(alias string) *{{.StructName}} { return {{.ConstructorName}}(alias) }

// {{.ExportName}} is the package-level accessor for the "{{.TableName}}" table.
var {{.ExportName}} = {{.ConstructorName}}("")
`

// tableTemplate is the parsed table template.
var tableTemplate = template.Must(template.New("table").Parse(tableTemplateText))

// titleFirst upper-cases the first rune of s, leaving the remainder unchanged.
// It converts an unexported struct name into its constructor suffix, for example
// "bookTable" into "BookTable" so that the constructor reads "newBookTable".
func titleFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] -= 'a' - 'A'
	}
	return string(runes)
}

// EmitTable renders the generated source for one table into a package named pkg.
// The output is formatted with gofmt; if formatting fails, the unformatted
// source is returned alongside the error to aid debugging.
func EmitTable(pkg string, t TableSchema) (string, error) {
	imports := map[string]bool{gooqImport: true}

	columns := make([]templateColumn, 0, len(t.Columns))
	for _, c := range t.Columns {
		mapping := mapSQLType(c.DataType, c.Nullable)
		for _, imp := range mapping.imports {
			imports[imp] = true
		}
		columns = append(columns, templateColumn{
			Field:       fieldName(c.Name),
			Type:        mapping.fieldType,
			Constructor: mapping.constructor,
			Column:      c.Name,
		})
	}

	importPaths := make([]string, 0, len(imports))
	for imp := range imports {
		importPaths = append(importPaths, imp)
	}
	sort.Strings(importPaths)

	sn := structName(t.Name)
	data := templateTable{
		Package:         pkg,
		Imports:         importPaths,
		StructName:      sn,
		ConstructorName: "new" + titleFirst(sn),
		ExportName:      exportName(t.Name),
		TableName:       t.Name,
		Columns:         columns,
	}

	var buf bytes.Buffer
	if err := tableTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering table %q: %w", t.Name, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting table %q: %w\n--- source ---\n%s", t.Name, err, buf.String())
	}
	return string(formatted), nil
}
