// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"github.com/cgardev/gooq"
)

// authorTable is the generated typed accessor for the "author" table.
type authorTable struct {
	gooq.TableImpl
	Id   gooq.NumericField[int64]
	Name gooq.StringField
}

func newAuthorTable(alias string) *authorTable {
	base := gooq.NewTable("author").WithAlias(alias)
	return &authorTable{
		TableImpl: base,
		Id:        gooq.NewNumericField[int64](base, "id"),
		Name:      gooq.NewStringField(base, "name"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *authorTable) As(alias string) *authorTable { return newAuthorTable(alias) }

// Author is the package-level accessor for the "author" table.
var Author = newAuthorTable("")
