// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"github.com/cgardev/gooq"
)

// bookTable is the generated typed accessor for the "book" table.
type bookTable struct {
	gooq.TableImpl
	Id       gooq.NumericField[int64]
	Title    gooq.StringField
	Price    gooq.NumericField[float64]
	AuthorId gooq.NumericField[int64]
}

func newBookTable(alias string) *bookTable {
	base := gooq.NewTable("book").WithAlias(alias)
	return &bookTable{
		TableImpl: base,
		Id:        gooq.NewNumericField[int64](base, "id"),
		Title:     gooq.NewStringField(base, "title"),
		Price:     gooq.NewNumericField[float64](base, "price"),
		AuthorId:  gooq.NewNumericField[int64](base, "author_id"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *bookTable) As(alias string) *bookTable { return newBookTable(alias) }

// PrimaryKey returns the primary key column names in key order.
func (t *bookTable) PrimaryKey() []string { return nil }

// Uniques returns each unique constraint as its ordered column names.
func (t *bookTable) Uniques() [][]string { return nil }

// ForeignKeys returns the foreign key constraints declared on the table.
func (t *bookTable) ForeignKeys() []gooq.ForeignKeyMeta {
	return []gooq.ForeignKeyMeta{}
}

// Book is the package-level accessor for the "book" table.
var Book = newBookTable("")
