// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"github.com/cgardev/gooq"
	"time"
)

// authorTable is the generated typed accessor for the "author" table.
type authorTable struct {
	gooq.TableImpl
	Id        gooq.StringField
	Name      gooq.StringField
	Email     gooq.StringField
	Metadata  gooq.Field[[]byte]
	CreatedAt gooq.Field[time.Time]
}

func newAuthorTable(alias string) *authorTable {
	base := gooq.NewTable("author").WithAlias(alias)
	return &authorTable{
		TableImpl: base,
		Id:        gooq.NewStringField(base, "id"),
		Name:      gooq.NewStringField(base, "name"),
		Email:     gooq.NewStringField(base, "email"),
		Metadata:  gooq.NewField[[]byte](base, "metadata"),
		CreatedAt: gooq.NewField[time.Time](base, "created_at"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *authorTable) As(alias string) *authorTable { return newAuthorTable(alias) }

// Author is the package-level accessor for the "author" table.
var Author = newAuthorTable("")
