// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"database/sql"
	"github.com/cgardev/gooq"
)

// bookOverviewTable is the generated typed accessor for the "book_overview" view.
type bookOverviewTable struct {
	gooq.TableImpl
	BookId     gooq.Field[sql.Null[string]]
	Title      gooq.Field[sql.Null[string]]
	Status     gooq.Field[sql.Null[BookStatus]]
	AuthorName gooq.Field[sql.Null[string]]
}

func newBookOverviewTable(alias string) *bookOverviewTable {
	base := gooq.NewTable("book_overview").WithAlias(alias)
	return &bookOverviewTable{
		TableImpl:  base,
		BookId:     gooq.NewField[sql.Null[string]](base, "book_id"),
		Title:      gooq.NewField[sql.Null[string]](base, "title"),
		Status:     gooq.NewField[sql.Null[BookStatus]](base, "status"),
		AuthorName: gooq.NewField[sql.Null[string]](base, "author_name"),
	}
}

// As returns the view under an alias, with every column re-qualified.
func (t *bookOverviewTable) As(alias string) *bookOverviewTable { return newBookOverviewTable(alias) }

// BookOverview is the package-level accessor for the "book_overview" view.
var BookOverview = newBookOverviewTable("")
