// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"
	"github.com/cgardev/gooq"
	"time"
)

// bookTable is the generated typed accessor for the "book" table.
type bookTable struct {
	gooq.TableImpl
	Id          gooq.StringField
	AuthorId    gooq.StringField
	EditorId    gooq.Field[sql.Null[string]]
	Title       gooq.StringField
	Subtitle    gooq.Field[sql.Null[string]]
	Price       gooq.NumericField[float64]
	PageCount   gooq.NumericField[int64]
	InPrint     gooq.Field[bool]
	Status      gooq.Field[BookStatus]
	Attributes  gooq.Field[json.RawMessage]
	PublishedAt gooq.Field[sql.Null[time.Time]]
	CreatedAt   gooq.Field[time.Time]
}

func newBookTable(alias string) *bookTable {
	base := gooq.NewTable("book").WithAlias(alias)
	return &bookTable{
		TableImpl:   base,
		Id:          gooq.NewStringField(base, "id"),
		AuthorId:    gooq.NewStringField(base, "author_id"),
		EditorId:    gooq.NewField[sql.Null[string]](base, "editor_id"),
		Title:       gooq.NewStringField(base, "title"),
		Subtitle:    gooq.NewField[sql.Null[string]](base, "subtitle"),
		Price:       gooq.NewNumericField[float64](base, "price"),
		PageCount:   gooq.NewNumericField[int64](base, "page_count"),
		InPrint:     gooq.NewField[bool](base, "in_print"),
		Status:      gooq.NewField[BookStatus](base, "status"),
		Attributes:  gooq.NewField[json.RawMessage](base, "attributes"),
		PublishedAt: gooq.NewField[sql.Null[time.Time]](base, "published_at"),
		CreatedAt:   gooq.NewField[time.Time](base, "created_at"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *bookTable) As(alias string) *bookTable { return newBookTable(alias) }

// PrimaryKey returns the primary key column names in key order.
func (t *bookTable) PrimaryKey() []string { return []string{"id"} }

// Uniques returns each unique constraint as its ordered column names.
func (t *bookTable) Uniques() [][]string { return nil }

// ForeignKeys returns the foreign key constraints declared on the table.
func (t *bookTable) ForeignKeys() []gooq.ForeignKeyMeta {
	return []gooq.ForeignKeyMeta{
		{Name: "book_author_id_fkey", Columns: []string{"author_id"}, RefTable: "author", RefColumns: []string{"id"}},
		{Name: "book_editor_id_fkey", Columns: []string{"editor_id"}, RefTable: "author", RefColumns: []string{"id"}},
	}
}

// Book is the package-level accessor for the "book" table.
var Book = newBookTable("")
