// Code generated by gooq-gen; DO NOT EDIT.

package db

// BookStatus is the Go named type for the "book_status" enum.
type BookStatus string

const (
	BookStatusDraft      BookStatus = "draft"
	BookStatusInPrint    BookStatus = "in_print"
	BookStatusOutOfPrint BookStatus = "out_of_print"
)
