// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"database/sql"
	"github.com/cgardev/gooq"
	"time"
)

// reviewTable is the generated typed accessor for the "review" table.
type reviewTable struct {
	gooq.TableImpl
	Id       gooq.StringField
	BookId   gooq.StringField
	Reviewer gooq.StringField
	Rating   gooq.NumericField[int64]
	Body     gooq.Field[sql.Null[string]]
	PostedAt gooq.Field[time.Time]
}

func newReviewTable(alias string) *reviewTable {
	base := gooq.NewTable("review").WithAlias(alias)
	return &reviewTable{
		TableImpl: base,
		Id:        gooq.NewStringField(base, "id"),
		BookId:    gooq.NewStringField(base, "book_id"),
		Reviewer:  gooq.NewStringField(base, "reviewer"),
		Rating:    gooq.NewNumericField[int64](base, "rating"),
		Body:      gooq.NewField[sql.Null[string]](base, "body"),
		PostedAt:  gooq.NewField[time.Time](base, "posted_at"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *reviewTable) As(alias string) *reviewTable { return newReviewTable(alias) }

// Review is the package-level accessor for the "review" table.
var Review = newReviewTable("")
