// Code generated by gooq-gen; DO NOT EDIT.

package db

import (
	"github.com/cgardev/gooq"
)

// tagTable is the generated typed accessor for the "tag" table.
type tagTable struct {
	gooq.TableImpl
	Id     gooq.StringField
	BookId gooq.StringField
	Label  gooq.StringField
}

func newTagTable(alias string) *tagTable {
	base := gooq.NewTable("tag").WithAlias(alias)
	return &tagTable{
		TableImpl: base,
		Id:        gooq.NewStringField(base, "id"),
		BookId:    gooq.NewStringField(base, "book_id"),
		Label:     gooq.NewStringField(base, "label"),
	}
}

// As returns the table under an alias, with every column re-qualified.
func (t *tagTable) As(alias string) *tagTable { return newTagTable(alias) }

// PrimaryKey returns the primary key column names in key order.
func (t *tagTable) PrimaryKey() []string { return []string{"id"} }

// Uniques returns each unique constraint as its ordered column names.
func (t *tagTable) Uniques() [][]string { return [][]string{{"book_id", "label"}} }

// ForeignKeys returns the foreign key constraints declared on the table.
func (t *tagTable) ForeignKeys() []gooq.ForeignKeyMeta {
	return []gooq.ForeignKeyMeta{
		{Name: "tag_book_id_fkey", Columns: []string{"book_id"}, RefTable: "book", RefColumns: []string{"id"}},
	}
}

// Tag is the package-level accessor for the "tag" table.
var Tag = newTagTable("")
